### ISSUE TITLE
How to define the semantic type of objects in a CSV file & default values

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#82] opened 2014-12-01 13:09 UTC
Admin: new thread broken out from existing issue #81 

@iherman proposed that a data publisher might include a `type` (`rdf:type`) column within the table that would assert the type for the object described by the row.

I can see this pattern working ... but most often the object described in _every row_ of a CSV file has the same type. See [Use Case #21 - Publication of Biodiversity Information from GBIF using the Darwin Core Archive Standard](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-PublicationOfBiodiversityInformation) where every record in the file is of type [Occurrence](http://rs.tdwg.org/dwc/terms/Occurrence) (see example 34: `rowType="http://rs.tdwg.org/dwc/terms/Occurrence"`).

In this case, I would like to be able to express the type of the row object in the metadata.

One way to achieve this would be to include an _optional_ `column` definition in the metadata for `type` and to assert a default value for cells in that column. Requirement [R-SpecificationOfPropertyValuePairForEachRow](http://w3c.github.io/csvw/use-cases-and-requirements/#R-SpecificationOfPropertyValuePairForEachRow) shows this in action - again using as example Darwin Core albeit for a different purpose. 

For example ...

```
    "columns": [{
      "name": "type",
      "predicateURL": "rdf:type",
      "dc:description": "Type of object described by each row.",
      "datatype": "anyURI",
      "required": false,
      "default": "http://rs.tdwg.org/dwc/terms/Occurrence"
    }
```

**Comment by iherman** [comment] 2014-12-01 13:24
I understand the intention, I do not understand the example... The example looks as if one would add a new, artificial column that does not appear in the data but that would be processed anyway as if it was there? Or do you mean to say that, in general, I may have a `default` value for the predicate in case the value is nil (i.e., the column is till in the original CSV file but mostly empty)?

**Comment by 6a6d74** [comment] 2014-12-01 13:41
The default value would apply in both situations ...
- if the _column_ was not present, or
- if the _cell value_ was considered `null` (e.g. an empty cell or one where the missing value token was used)

In my example to set the `type` I was creating an artificial column.

**Comment by iherman** [comment] 2014-12-01 13:47
> On 01 Dec 2014, at 14:41 , Jeremy Tandy notifications@github.com wrote:
> 
> The default value would apply in both situations ...
> 
>   • if the column was not present, or
>   • if the cell value was considered null (e.g. an empty cell or one where the missing value token was used)
> In my example to set the type I was creating an artificial column.

My gut is a bit afraid of that artificial column idea:-) If what we want is to assign a repeated value (whatever that is) to each row, which I can see a utility for, then I would prefer to have a separate entry under 'scheme', rather than adding an artificial column... I think it would greatly complicate, eg, implementations if one cannot rely on having the column structures having a 1-1 correspondence with the real columns in the data...

I may just be too afraid of the jungle.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment] 2014-12-01 15:40
Fair point. In the interim, this is not going to be included in the mapping spec. Will be focusing on the simplest _simple mapping_ first.

**Comment by gkellogg** [comment] 2014-12-01 18:02
I believe that at the F2F we discussed describing column metadata for missing columns as a way of injecting more information, for example, by combining multiple column values together to create a new value. This could also be used to inject static information, such as an rdf:type for the row.

**Comment by 6a6d74** [comment] 2014-12-02 09:42
@gkellogg: that's kind of the plan that I had here ... thanks for clarifying.

**Comment by JeniT** [comment] 2015-02-04 14:30
Closing as duplicate of #26

**Closed as completed by JeniT** 2015-02-04 14:30 UTC
Labels: CSV to RDF mapping, Metadata vocabulary document, Requires telcon discussion/decision
