### ISSUE TITLE
rdf source for templates

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#137] opened 2014-12-23 12:04 UTC
The current text for template source says:

> If the value is "rdf", it should similarly first be transformed to XML based on the simple mapping defined in Generating RDF from Tabular Data on the Web.

First of all, it should probably say `RDF/XML` rather than just `XML`. However, I do not think we should require the tool to produce that particular RDF serialization or, rather, not to have a standard way of referring to another serialization. Something like `rdf turtle`, `rdf json-ld`, or `rdf xml` should be allowed for possible values for `source`.

**Comment by JeniT** [comment] 2015-02-04 16:40
Closing as duplicate of #83

**Closed as completed by JeniT** 2015-02-04 16:40 UTC
Labels: Metadata vocabulary document
